import Header from "./Components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Zitro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
